name: Rust

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install OS Dependencies
        run: |
          sudo apt-get update
          sudo apt install -y clang libssl-dev llvm libudev-dev make protobuf-compiler pkg-config build-essential
      - uses: actions/checkout@v4
      - name: ⚡ Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install minimal stable with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          components: rust-src
      - name: Build
        run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          path: |
            wm-devnet-chainspec.json
            utils/session_key_tools/split_session_key.sh
            target/release/aya-node
